pipeline:
    install_npm_packages:
        image: node:4
        environment:
            - NPM_CONFIG_LOGLEVEL=warn
        commands:
            - npm install
            - npm test

    dogfood_versioning:
        image: node:4
        commands:
            - npm start
            - git config --add user.name steve-gray
            - git config --add user.email steve@eventualconsistency.net
            - git push --set-upstream origin master
        when:
            branch: master
            event: push

    
