pipeline:
    install_npm_packages:
        image: node:4
        environment:
            - NPM_CONFIG_LOGLEVEL=warn
        commands:
            - npm install
            - npm test

    dogfood_versioning:
        image: node:4
        commands:
            - git config --global user.name steve-gray
            - git config --global user.email steve@eventualconsistency.net
            - npm start
        when:
            branch: master
            event: push
        
    git_push:
        image: plugins/git-push
        remote_name: origin
        when:
            branch: master
            event: push