pipeline:
    # Preamble to make sure project is ready.
    install_npm_packages:
        image: node:4
        environment:
            - NPM_CONFIG_LOGLEVEL=warn
        commands:
            - npm install
            - npm test

    # Publish the test plugin.
    docker_publish_smoke:
        image: plugins/docker
        repo: eventualconsistency/semantique
        tag: smoke
        when:
            branch: master
            event: push

    # Use the smoke version to apply our own versioning rules.
    run_semantique_self:
        image: eventualconsistency/semantique:smoke
        pull: true
        when:
            branch: master
            event: push

    # Push the latest and onbuild version tags.
    docker_publish_release:
        image: plugins/docker
        repo: eventualconsistency/semantique
        tag:
            - latest
            - onbuild
        when:
            branch: master
            event: push
