pipeline:
    install_npm_packages:
        image: node:4
        environment:
            - NPM_CONFIG_LOGLEVEL=warn
        commands:
            - npm install
            - npm test

    # Publish the test plugin.
    docker_publishing:
        image: plugins/docker
        repo: eventualconsistency/semantique
        tag: onbuild
        when:
            branch: master
            event: push

    # Apply our own versioning.
    dogfood_versioning:
        image: eventualconsistency/semantique:onbuild
        pull: true
        commands:
            - git config --global user.name steve-gray
            - git config --global user.email steve@eventualconsistency.net
            - env
            - npm start
            - git push origin master
        when:
            branch: master
            event: push
    
    docker_publishing:
        image: plugins/docker
        repo: eventualconsistency/semantique
        tag: latest
        when:
            branch: master
            event: push
