pipeline:
    install_npm_packages:
        image: node:4
        environment:
            - NPM_CONFIG_LOGLEVEL=warn
        commands:
            - npm install
            - npm test

    docker_publishing:
        image: plugins/docker
        repo: eventualconsistency/semantique
        tag: onbuild
        when:
            branch: master
            event: push

    dogfood_versioning:
        image: eventualconsistency/semantique:onbuild
        commands:
            - git config --global user.name steve-gray
            - git config --global user.email steve@eventualconsistency.net
            - npm start
        when:
            branch: master
            event: push

    docker_publishing:
        image: plugins/docker
        repo: eventualconsistency/semantique
        tag: latest
        when:
            branch: master
            event: push
